#spring.application.name=ordering

# ??? SERVER ???
server.port=8080

# ??? DATABASE ???
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PWD}
spring.datasource.username=${DB_USER}
#spring.datasource.url=jdbc:mysql://localhost:3306/retail_ordering?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=yourpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ??? JPA ???
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ??? SWAGGER ???
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# ??? APP NAME ???
spring.application.name=retail-ordering


jwt.secret=3f8b2c1d9e4a7f6b0c5d2e8a1b4c7f9d3e6a0b5c8d1f4a7e2b9c6d3f0a1e4b7
jwt.expiration=86400000
app.cors.allowed-origins=http://localhost:5173
